[package]
name = "datafeed-cache-shared"
edition = "2024"
version = "1.2.2"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4.40", features = ["serde"] }