services:
  df-cache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8000/tcp"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health-check" ]
      interval: 5m
      timeout: 20s
      retries: 3
      start_period: 5s
      start_interval: 10s
    environment:
      - RUST_LOG=info