name: Code-Style Check

# Run only if a *.ts file has changed (i.e. anything relevant)
on:
  push:
    branches: [ "dev" ]
    paths:
      - "**.ts"
  pull_request:
    branches: [ "dev" ]
    paths:
      - "**.ts"

jobs:
  code-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettier Check
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: "--check **/*.ts"