name: Code-Style Check

on:
  push:
    branches: [ "dev" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  code-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prettier Check
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: "--check **/*.ts"
          only_changed: true
